import { useState } from 'react';
import { Badge, Empty, Panel, Stats } from '../components/ui';
import { CategoryChart, DailyChart } from '../components/Charts';
import { categories, regions, type Occurrence } from '../types';
import { signals } from '../helpers';
export function Alerts({ records }: { records: Occurrence[] }) {
  const [region,setRegion]=useState(''); const [category,setCategory]=useState(''); const [level,setLevel]=useState('');
  const all=signals(records); const alerts=all.filter(a => (!region || a.region === region) && (!category || a.category === category) && (!level || a.severity === level));
  return <><Stats items={[{value:all.length,label:'Alertas ativos',note:'Grupos com 3 ou mais relatos'},{value:all.filter(a => a.severity === 'Crítico').length,label:'Críticos',note:'Grupos com 6 ou mais relatos',color:'#ef4444'},{value:records.filter(r => r.status !== 'Resolvida' && r.priority === 'Alta').length,label:'Chamados prioritários',note:'Triagem pendente de validação'},{value:all.length,label:'Recomendações',note:'Vistoria conjunta sugerida'}]} />
    <div className="filters"><span className="filters-label">Filtros rápidos</span><div className="filters-controls"><select aria-label="Nível do alerta" value={level} onChange={e => setLevel(e.target.value)}><option value="">Todos os níveis</option><option>Crítico</option><option>Atenção</option></select><select aria-label="Categoria do alerta" value={category} onChange={e => setCategory(e.target.value)}><option value="">Todas as categorias</option>{categories.map(c => <option key={c}>{c}</option>)}</select><select aria-label="Região do alerta" value={region} onChange={e => setRegion(e.target.value)}><option value="">Todas as regiões</option>{regions.map(r => <option key={r}>{r}</option>)}</select><Badge tone="green">Regras demonstrativas v1</Badge></div></div>
    <div className="alerts-grid"><Panel title="Sinais detectados" subtitle="Priorizados por volume e recorrência"><div className="alert-list">{alerts.map(a => <article key={a.title} className={'alert-row '+(a.severity === 'Crítico' ? 'critical' : '')}><div><Badge>{a.severity}</Badge><h3>{a.title}</h3><p>{a.description}</p><small>{a.count} ocorrências em aberto · {a.region}</small></div><a className="btn btn-light" href={'#/gestor/mapa?regiao='+encodeURIComponent(a.region)}>Ver região</a></article>)}{!alerts.length ? <Empty title="Nenhum sinal para estes filtros." text="O agrupamento precisa de pelo menos 3 relatos em aberto da mesma categoria e região." /> : null}</div></Panel>
      <Panel className="intelligence" title="Inteligência da cidade" subtitle="Síntese demonstrativa dos sinais mais relevantes">{all[0] ? <div className="priority-box"><small>PRIORIDADE RECOMENDADA</small><h3>Inspeção em {all[0].region}</h3><p>{all[0].description}</p><a className="btn btn-teal full-width" href="#/gestor/ocorrencias">Abrir fila de atendimento</a></div> : <p>Sem concentrações no período.</p>}<h3 className="spaced-title">Categorias monitoradas</h3><CategoryChart records={records} /><p className="analysis-explanation">Como calculamos: agrupamos os chamados abertos por categoria e região. A partir de 3 registros há um sinal de atenção; a partir de 6, um alerta crítico. Estes critérios são acadêmicos e devem ser validados.</p></Panel></div>
    <div className="dashboard-bottom"><Panel title="Evolução dos registros" subtitle="Novos relatos por dia nos últimos 7 dias"><DailyChart records={records} /></Panel><Panel title="Recomendações pendentes" subtitle="Ações sugeridas para avaliação humana">{all.map(a => <div className="recommendation" key={a.title}><div><strong>Vistoriar {a.category.toLowerCase()}</strong><small>{a.region}</small></div><Badge>{a.severity === 'Crítico' ? 'Alta' : 'Média'}</Badge></div>)}{!all.length ? <Empty title="Nenhuma recomendação." text="O sistema monitora os relatos do período." /> : null}</Panel></div>
  </>;
}
