import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from 'react';
import { api, type Actor } from '../api';
import { statuses, type Occurrence } from '../types';
import { Badge, Empty, ErrorBox, Panel, Stats } from '../components/ui';
import { dateTime } from '../helpers';

const profiles: Record<Exclude<Actor,'gestor-demo'>,{name:string;label:string}>={ 'colab-joao':{name:'João Silva',label:'Pavimentação'},'colab-maria':{name:'Maria Oliveira',label:'Iluminação'},'colab-carlos':{name:'Carlos Santos',label:'Limpeza urbana'} };
const isOverdue=(task:Occurrence)=>Boolean(task.dueAt&&new Date(task.dueAt).getTime()<Date.now()&&task.status!=='Resolvida');
async function photoFrom(e:ChangeEvent<HTMLInputElement>,set:(value:string|null)=>void,setError:(value:string)=>void){const file=e.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png'].includes(file.type)||file.size>2*1024*1024){set(null);setError('Envie uma foto JPG ou PNG de até 2 MB.');return;}setError('');set(await new Promise<string>(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(file);}));}

export function CollaboratorPortal(){
  const [actor,setActor]=useState<Exclude<Actor,'gestor-demo'>>('colab-joao'),[tasks,setTasks]=useState<Occurrence[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[note,setNote]=useState(''),[progress,setProgress]=useState(50),[photo,setPhoto]=useState<string|null>(null),[selected,setSelected]=useState<string|null>(null),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState(''),[confirmCompletion,setConfirmCompletion]=useState(false);
  const load=async()=>{setLoading(true);try{setTasks(await api.collaboratorTasks(actor));setError('');}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar tarefas.');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[actor]);
  const totals=useMemo(()=>({assigned:tasks.filter(t=>t.status!=='Resolvida').length,running:tasks.filter(t=>t.status==='Em execução').length,waiting:tasks.filter(t=>t.status==='Aguardando validação').length,done:tasks.filter(t=>t.status==='Resolvida').length}),[tasks]);
  const visible=useMemo(()=>{const search=query.trim().toLocaleLowerCase('pt-BR');return tasks.filter(task=>(!statusFilter||task.status===statusFilter)&&(!search||`${task.title} ${task.protocol} ${task.address} ${task.neighborhood}`.toLocaleLowerCase('pt-BR').includes(search))).sort((a,b)=>Number(isOverdue(b))-Number(isOverdue(a))||Number(b.priority==='Alta')-Number(a.priority==='Alta')||b.createdAt.localeCompare(a.createdAt));},[query,statusFilter,tasks]);
  const current=tasks.find(t=>t.id===selected)||visible.find(t=>t.status==='Em execução')||visible.find(t=>t.status==='Programada')||visible[0];
  async function run(id:string,kind:'start'|'progress'|'conclude',e?:FormEvent){e?.preventDefault();setBusy(kind);setError('');setNotice('');try{if(kind==='start')await api.start(id,actor);if(kind==='progress')await api.progress(id,{note,progress,photo},actor);if(kind==='conclude')await api.conclude(id,{note,photo},actor);setNote('');setPhoto(null);setConfirmCompletion(false);setNotice(kind==='start'?'Serviço iniciado. O Kanban foi atualizado.':kind==='progress'?'Andamento registrado no histórico.':'Conclusão enviada para validação do gestor.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir a ação.');}finally{setBusy('');}}
  return <div className="collaborator-shell"><header className="collaborator-header"><a href="#/" className="collaborator-brand">Observa<span>Marília</span></a><select aria-label="Perfil demonstrativo" value={actor} onChange={e=>{setActor(e.target.value as Exclude<Actor,'gestor-demo'>);setSelected(null);setStatusFilter('');setQuery('');}}>{Object.entries(profiles).map(([id,p])=><option key={id} value={id}>{p.name} · {p.label}</option>)}</select></header><main className="collaborator-main"><div className="collaborator-hero"><div><p>Bom dia,</p><h1>Olá, {profiles[actor].name.split(' ')[0]}!</h1><span>Confira suas atividades de campo e atualize cada serviço.</span></div><a className="btn btn-light" href="#/gestor/equipes">Ver operação</a></div><Stats className="collaborator-stats" items={[{value:totals.assigned,label:'Atribuídas',color:'#2563eb'},{value:totals.running,label:'Em execução',color:'#f97316'},{value:totals.waiting,label:'Aguardando aprovação',color:'#f59e0b'},{value:totals.done,label:'Concluídas',color:'#10b981'}]}/><ErrorBox error={error}/>{notice?<p className="success-message" role="status">{notice}</p>:null}
    {loading?<div className="loading" role="status">Carregando tarefas…</div>:<div className="portal-grid"><section><div className="portal-list-heading"><div><h2 className="portal-title">Minhas atividades</h2><small>{visible.length} tarefa(s) encontrada(s)</small></div><div className="task-filters"><label className="visually-hidden" htmlFor="task-search">Buscar tarefa</label><input id="task-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar título, protocolo ou endereço" />{query?<button className="clear-search" type="button" onClick={()=>setQuery('')} aria-label="Limpar busca">×</button>:null}<label className="visually-hidden" htmlFor="task-status">Filtrar por status</label><select id="task-status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Todos os status</option>{statuses.map(status=><option key={status}>{status}</option>)}</select></div></div>{!visible.length?<Empty title={tasks.length?'Nenhuma tarefa encontrada.':'Nenhuma tarefa atribuída.'} text={tasks.length?'Limpe a busca ou escolha outro status.':'Quando um gestor direcionar um serviço à sua equipe, ele aparecerá aqui.'}/>:<><div className="task-list">{visible.filter(task=>task.status!=='Resolvida').map(task=><article key={task.id} className={'worker-task '+(task.id===current?.id?'selected ':'')+(isOverdue(task)?'overdue':'')}><div className="task-top"><Badge>{task.priority}</Badge><small>{task.protocol}</small></div><h3>{task.title}</h3><p>{task.address} · {task.neighborhood}</p><div className="task-meta"><Badge>{task.status}</Badge><span>{task.team||'Equipe não definida'}</span></div><small className={isOverdue(task)?'due overdue-text':'due'}>{task.dueAt?`${isOverdue(task)?'Prazo vencido':'Prazo'}: ${dateTime(task.dueAt)}`:'Prazo não informado'}</small><button className="btn btn-outline" onClick={()=>setSelected(task.id)}>Abrir tarefa</button></article>)}</div><h2 className="portal-title history-title">Histórico de serviços</h2>{visible.filter(task=>task.status==='Resolvida').slice(0,3).map(task=><article className="completed-row" key={task.id}><div><strong>{task.title}</strong><small>{task.protocol} · {task.team}</small></div><Badge tone="green">Concluído</Badge></article>)}</>}</section>
      {current?<Panel className="work-panel" title={current.title} subtitle={`${current.protocol} · ${current.category}`}><div className="work-address"><strong>{current.address}</strong><span>{current.neighborhood} · {current.region}</span></div><div className="badges"><Badge>{current.priority}</Badge><Badge>{current.status}</Badge>{isOverdue(current)?<Badge tone="red">Prazo vencido</Badge>:null}</div>{current.status==='Programada'?<button className="btn worker-action" disabled={busy==='start'} onClick={()=>void run(current.id,'start')}>{busy==='start'?'Iniciando…':'▶ Iniciar serviço'}</button>:current.status==='Em execução'?<form className="execution-form" onSubmit={e=>void run(current.id,'progress',e)} noValidate><label>Registrar andamento<textarea required minLength={5} value={note} onChange={e=>setNote(e.target.value)} placeholder="O que foi realizado? Há alguma dificuldade?" rows={3}/></label><label>Progresso: {progress}%<input type="range" min="0" max="100" value={progress} onChange={e=>setProgress(Number(e.target.value))}/></label><label>Foto de evidência <input type="file" accept="image/png,image/jpeg" onChange={e=>void photoFrom(e,setPhoto,setError)}/></label><button className="btn btn-outline" disabled={busy==='progress'}>{busy==='progress'?'Registrando…':'Salvar andamento'}</button><button type="button" className="btn worker-action" disabled={busy==='conclude'||note.trim().length<10} onClick={()=>setConfirmCompletion(true)}>{busy==='conclude'?'Enviando…':'Enviar conclusão para validação'}</button></form>:current.status==='Aguardando validação'?<div className="waiting-validation"><strong>Conclusão enviada</strong><p>O gestor precisa validar o serviço antes de ele aparecer como resolvido para o cidadão.</p></div>:<div className="waiting-validation"><strong>Serviço concluído</strong><p>Este atendimento já foi validado.</p></div>}<h3 className="execution-title">Atualizações da execução</h3><div className="execution-history">{current.executionUpdates?.length?current.executionUpdates.map(update=><div key={update.id}><strong>{update.kind==='conclusao'?'Conclusão':'Andamento'} · {update.progress??0}%</strong><p>{update.note}</p><small>{update.collaboratorName} · {dateTime(update.createdAt)}</small></div>):<small>Nenhum registro operacional ainda.</small>}</div></Panel>:null}</div>}
    {confirmCompletion&&current?<div className="confirmation-backdrop" role="presentation"><section className="confirmation-dialog" role="alertdialog" aria-modal="true" aria-labelledby="completion-title" aria-describedby="completion-description"><h2 id="completion-title">Enviar conclusão?</h2><p id="completion-description">O serviço passará para “Aguardando validação”. O gestor ainda poderá aprovar ou solicitar correção.</p><div><button className="btn btn-light" type="button" onClick={()=>setConfirmCompletion(false)}>Continuar editando</button><button className="btn worker-action" type="button" onClick={()=>void run(current.id,'conclude')}>Confirmar envio</button></div></section></div>:null}</main></div>;
}
