import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from 'react';
import { api, type Actor } from '../api';
import type { Occurrence } from '../types';
import { Badge, Empty, ErrorBox, Panel, Stats } from '../components/ui';
import { dateTime } from '../helpers';

const profiles: Record<Exclude<Actor,'gestor-demo'>,{name:string;label:string}>={ 'colab-joao':{name:'João Silva',label:'Pavimentação'},'colab-maria':{name:'Maria Oliveira',label:'Iluminação'},'colab-carlos':{name:'Carlos Santos',label:'Limpeza urbana'} };
async function photoFrom(e:ChangeEvent<HTMLInputElement>,set:(value:string|null)=>void){const file=e.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png'].includes(file.type)||file.size>2*1024*1024){set(null);return;}set(await new Promise<string>(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(file);}));}
export function CollaboratorPortal(){
  const [actor,setActor]=useState<Exclude<Actor,'gestor-demo'>>('colab-joao'),[tasks,setTasks]=useState<Occurrence[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[note,setNote]=useState(''),[progress,setProgress]=useState(50),[photo,setPhoto]=useState<string|null>(null),[selected,setSelected]=useState<string|null>(null),[notice,setNotice]=useState('');
  const load=async()=>{setLoading(true);try{setTasks(await api.collaboratorTasks(actor));setError('');}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar tarefas.');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[actor]);
  const current=tasks.find(t=>t.id===selected)||tasks.find(t=>t.status==='Em execução')||tasks.find(t=>t.status==='Programada');
  const totals=useMemo(()=>({assigned:tasks.filter(t=>!['Resolvida'].includes(t.status)).length,running:tasks.filter(t=>t.status==='Em execução').length,waiting:tasks.filter(t=>t.status==='Aguardando validação').length,done:tasks.filter(t=>t.status==='Resolvida').length}),[tasks]);
  async function run(id:string,kind:'start'|'progress'|'conclude',e?:FormEvent){e?.preventDefault();setBusy(kind);setError('');setNotice('');try{if(kind==='start')await api.start(id,actor);if(kind==='progress')await api.progress(id,{note,progress,photo},actor);if(kind==='conclude')await api.conclude(id,{note,photo},actor);setNote('');setPhoto(null);setNotice(kind==='start'?'Serviço iniciado. O Kanban foi atualizado.':kind==='progress'?'Andamento registrado no histórico.':'Conclusão enviada para validação do gestor.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir a ação.');}finally{setBusy('');}}
  return <div className="collaborator-shell"><header className="collaborator-header"><a href="#/" className="collaborator-brand">Observa<span>Marília</span></a><select aria-label="Perfil demonstrativo" value={actor} onChange={e=>setActor(e.target.value as Exclude<Actor,'gestor-demo'>)}>{Object.entries(profiles).map(([id,p])=><option key={id} value={id}>{p.name} · {p.label}</option>)}</select></header><main className="collaborator-main"><div className="collaborator-hero"><div><p>Bom dia,</p><h1>Olá, {profiles[actor].name.split(' ')[0]}!</h1><span>Confira suas atividades de campo e atualize cada serviço.</span></div><a className="btn btn-light" href="#/gestor/equipes">Ver operação</a></div><Stats className="collaborator-stats" items={[{value:totals.assigned,label:'Atribuídas',color:'#2563eb'},{value:totals.running,label:'Em execução',color:'#f97316'},{value:totals.waiting,label:'Aguardando aprovação',color:'#f59e0b'},{value:totals.done,label:'Concluídas',color:'#10b981'}]}/><ErrorBox error={error}/>{notice?<p className="success-message" role="status">{notice}</p>:null}
    {loading?<div className="loading" role="status">Carregando tarefas…</div>:!tasks.length?<Empty title="Nenhuma tarefa atribuída." text="Quando um gestor direcionar um serviço à sua equipe, ele aparecerá aqui."/>:<div className="portal-grid"><section><h2 className="portal-title">Atividades prioritárias</h2><div className="task-list">{tasks.filter(t=>t.status!=='Resolvida').map(task=><article key={task.id} className={'worker-task '+(task.id===current?.id?'selected':'')}><div className="task-top"><Badge>{task.priority}</Badge><small>{task.protocol}</small></div><h3>{task.title}</h3><p>{task.address} · {task.neighborhood}</p><div className="task-meta"><Badge>{task.status}</Badge><span>{task.team}</span></div><small>Atribuída: {task.assignedAt?dateTime(task.assignedAt):'—'} {task.dueAt?`· Prazo: ${dateTime(task.dueAt)}`:''}</small><button className="btn btn-outline" onClick={()=>setSelected(task.id)}>Abrir tarefa</button></article>)}</div><h2 className="portal-title history-title">Histórico de serviços</h2>{tasks.filter(t=>t.status==='Resolvida').slice(0,3).map(task=><article className="completed-row" key={task.id}><strong>{task.title}</strong><Badge tone="green">Concluído</Badge></article>)}</section>
      {current?<Panel className="work-panel" title={current.title} subtitle={`${current.protocol} · ${current.category}`}><div className="work-address"><strong>{current.address}</strong><span>{current.neighborhood} · {current.region}</span></div><div className="badges"><Badge>{current.priority}</Badge><Badge>{current.status}</Badge></div>{current.status==='Programada'?<button className="btn worker-action" disabled={busy==='start'} onClick={()=>void run(current.id,'start')}>{busy==='start'?'Iniciando…':'▶ Iniciar serviço'}</button>:current.status==='Em execução'?<form className="execution-form" onSubmit={e=>void run(current.id,'progress',e)} noValidate><label>Registrar andamento<textarea required minLength={5} value={note} onChange={e=>setNote(e.target.value)} placeholder="O que foi realizado? Há alguma dificuldade?" rows={3}/></label><label>Progresso: {progress}%<input type="range" min="0" max="100" value={progress} onChange={e=>setProgress(Number(e.target.value))}/></label><label>Foto de evidência <input type="file" accept="image/png,image/jpeg" onChange={e=>void photoFrom(e,setPhoto)}/></label><button className="btn btn-outline" disabled={busy==='progress'}>{busy==='progress'?'Registrando…':'Salvar andamento'}</button><button type="button" className="btn worker-action" disabled={busy==='conclude'||note.trim().length<10} onClick={()=>void run(current.id,'conclude')}>{busy==='conclude'?'Enviando…':'Enviar conclusão para validação'}</button></form>:current.status==='Aguardando validação'?<div className="waiting-validation"><strong>Conclusão enviada</strong><p>O gestor precisa validar o serviço antes de ele aparecer como resolvido para o cidadão.</p></div>:<div className="waiting-validation"><strong>Serviço concluído</strong><p>Este atendimento já foi validado.</p></div>}<h3 className="execution-title">Atualizações da execução</h3><div className="execution-history">{current.executionUpdates?.map(update=><div key={update.id}><strong>{update.kind==='conclusao'?'Conclusão':'Andamento'} · {update.progress??0}%</strong><p>{update.note}</p><small>{update.collaboratorName} · {dateTime(update.createdAt)}</small></div>)||<small>Nenhum registro operacional ainda.</small>}</div></Panel>:null}</div>}</main></div>;
}
