import { useEffect, useState, type FormEvent } from 'react';
import { api } from '../api';
import { useData } from '../data';
import { nextStatus, teams, type Occurrence } from '../types';
import { Badge, ErrorBox, Panel, asset, PageHeading, ResponsiveAsset } from '../components/ui';
import { dateTime } from '../helpers';
export function Detail({ id, manager = false }: { id: string; manager?: boolean }) {
  const { records, refresh }=useData(); const [record,setRecord]=useState<Occurrence|null>(null); const [loading,setLoading]=useState(true);
  const [error,setError]=useState(''); const [team,setTeam]=useState<string>(teams[0]); const [note,setNote]=useState(''); const [busy,setBusy]=useState(false); const [saved,setSaved]=useState('');
  useEffect(() => { let active=true; setLoading(true); setError('');
    api.detail(id).then(r => { if(active) { setRecord(r); setTeam(r.team || teams[0]); } }).catch(e => { if(active) setError(e.message); }).finally(() => { if(active) setLoading(false); });
    return () => { active=false; };
  },[id]);
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); if(!record || !nextStatus[record.status] || busy) return;
    setBusy(true); setError(''); setSaved('');
    try { const updated=await api.update(id,{ status:nextStatus[record.status]!,team,note }); setRecord(updated); setNote(''); setSaved('Etapa atualizada e registrada no histórico.'); await refresh(); }
    catch(e) { setError(e instanceof Error ? e.message : 'Falha na atualização.'); }
    finally { setBusy(false); }
  }
  if(loading) return <div className="loading" role="status">Carregando ocorrência…</div>;
  if(!record) return <><ErrorBox error={error} /><a className="btn" href={manager ? '#/gestor/ocorrencias' : '#/meus-relatos'}>Voltar aos relatos</a></>;
  const similar=records.filter(r => r.id !== id && r.region === record.region && r.category === record.category && r.status !== 'Resolvida');
  return <>{!manager ? <PageHeading title="Detalhes da ocorrência" subtitle="Acompanhe o andamento do atendimento." action={<a className="btn btn-light" href="#/meus-relatos">Voltar aos relatos</a>} /> : <a className="text-button detail-back" href="#/gestor/ocorrencias">Voltar para a fila de ocorrências</a>}
    <Panel className="detail-summary"><div><h2>{record.title}</h2><p>Ocorrência aberta pela população e acompanhada pela equipe municipal.</p><div className="badges"><Badge>{record.priority}</Badge><Badge>{record.status}</Badge><Badge tone="gray">{record.category}</Badge><Badge tone="gray">{record.region}</Badge></div><small>Aberta em {dateTime(record.createdAt)}</small></div><div><small>ID {record.protocol}</small><Badge tone="green">{record.status === 'Resolvida' ? 'Atendimento concluído' : 'Acompanhamento ativo'}</Badge></div></Panel>
    <div className="detail-three"><Panel title="Informações do chamado" subtitle="Dados enviados pelo cidadão"><dl className="info-list">{[['Categoria',record.category],['Endereço',record.address],['Bairro',record.neighborhood],['Região',record.region],['Protocolo',record.protocol]].map(([k,v]) => <div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="detail-description"><small>DESCRIÇÃO</small><p>{record.description}</p></div></Panel>
      <Panel title="Foto da ocorrência" subtitle={record.photo ? 'Registro enviado pelo cidadão' : 'Ilustração do protótipo · foto não enviada'}><div className="detail-photo">{record.photo ? <img src={record.photo} alt={'Foto da ocorrência: '+record.title} /> : <ResponsiveAsset src={asset('10-2','imgPhotoMockup')} width={320} height={154} alt="Ilustração de uma via com buraco; não é uma foto deste chamado" />}</div><small className="photo-caption">{record.photo ? 'Foto original do relato' : 'Sem foto anexada a este relato'}</small></Panel>
      <Panel className="intelligence" title="Análise automática" subtitle="INTELIGÊNCIA DA CIDADE"><dl className="analysis-list"><div><dt>Classificação informada</dt><dd>{record.category}</dd></div><div><dt>Prioridade sugerida</dt><dd>{record.priority}</dd></div><div><dt>Relatos semelhantes</dt><dd>{similar.length} na mesma categoria e região</dd></div><div><dt>Método</dt><dd>Regras demonstrativas, sem modelo de IA</dd></div></dl><div className="suggestion">{record.reason}</div></Panel></div>
    <div className="detail-two"><Panel title="Localização e recorrência" subtitle="Agrupamento por categoria e região"><div className="location-detail"><div className="mini-map"><div className="mini-map-line horizontal" /><div className="mini-map-line vertical" /><img className="mini-halo" src={asset('10-2','imgHotspotHalo')} alt="" /><div className="mini-pin"><img src={asset('10-2','imgMainPin')} alt="" /><span>{similar.length+1}</span></div></div><div><h3>{record.region}</h3><p>{record.address}</p><strong>{similar.length}</strong><small>outros relatos em aberto no grupo</small><Badge tone="green">Agrupamento demonstrativo</Badge></div></div></Panel>
      <Panel title="Encaminhamento" subtitle="Responsáveis pelo atendimento">{manager && nextStatus[record.status] ? <form onSubmit={submit} className="assignment-form"><label htmlFor="team">Equipe<select id="team" aria-label="Equipe" value={team} onChange={e => setTeam(e.target.value)}>{teams.map(t => <option key={t}>{t}</option>)}</select></label><label htmlFor="note">Justificativa / atualização<textarea id="note" value={note} onChange={e => setNote(e.target.value)} minLength={5} maxLength={600} required rows={2} placeholder={record.status === 'Em execução' ? 'Descreva a solução realizada…' : 'Informe a ação realizada ou programada…'} /></label><div className="assignment-bottom"><span>Próxima etapa: <strong>{nextStatus[record.status]}</strong></span><button className="btn" disabled={busy}>{busy ? 'Salvando…' : record.status === 'Em análise' ? 'Enviar equipe' : record.status === 'Em execução' ? 'Concluir ocorrência' : 'Avançar etapa'}</button></div></form> : <dl className="info-list"><div><dt>Equipe</dt><dd>{record.team || 'Aguardando encaminhamento'}</dd></div><div><dt>Status</dt><dd>{record.status}</dd></div><div><dt>Conclusão</dt><dd>{record.resolvedAt ? dateTime(record.resolvedAt) : 'Ainda em atendimento'}</dd></div></dl>}<ErrorBox error={error} />{saved ? <p className="success-message" role="status">{saved}</p> : null}</Panel></div>
    <Panel title="Histórico da ocorrência" subtitle="Atualizações registradas desde a abertura"><ol className="timeline">{record.history.map((h,i) => <li key={i}><span className="timeline-dot"><img src={asset('10-2', ['imgTimelineNode','imgTimelineNode1','imgTimelineNode2','imgTimelineNode3','imgTimelineNode4'][Math.min(i,4)])} alt="" /><img className="timeline-inner" src={asset('10-2','imgTimelineInner')} alt="" /></span><small>{dateTime(h.createdAt)}</small><strong>{h.title}</strong><p>{h.note}</p></li>)}</ol><div className="timeline-note">Todos os eventos ficam registrados para rastreabilidade e transparência do atendimento.</div></Panel>
  </>;
}
