import { useData } from '../data';
import { stats } from '../helpers';
import { Badge, Panel, Stats } from '../components/ui';
import { CityMap } from '../components/CityMap';
export function Home() {
  const { records }=useData(); const s=stats(records);
  return <><section className="citizen-hero"><div className="hero-copy"><span className="live-tag"><span /> Cidade em tempo real</span><h1>Sua cidade, mais perto<br />de você.</h1><p>Veja o que está acontecendo em Marília, acompanhe problemas próximos e ajude a melhorar a cidade com um relato em poucos passos.</p><div className="hero-actions"><a className="btn btn-teal" href="#/relatar">+ Reportar problema</a><a className="btn btn-dark-light" href="#/mapa">Explorar o mapa</a></div></div><div className="city-now"><h2>Marília agora</h2><strong>{s.total}</strong><small>ocorrências registradas</small><div className="city-now-stats"><div><span className="dot green" /><strong>{s.resolved}</strong><small>resolvidas</small></div><div><span className="dot amber" /><strong>{s.open}</strong><small>em aberto</small></div><div><span className="dot teal" /><strong>{s.rate}%</strong><small>taxa de solução</small></div></div><p className="city-now-note">Dados fictícios da demonstração acadêmica</p></div></section>
    <Stats className="public-quick-stats" items={[{value:s.total,label:'Chamados recebidos'},{value:s.resolved,label:'Resolvidos'},{value:s.average,label:'Tempo médio'},{value:`${s.rate}%`,label:'Taxa de solução'}]} />
    <div className="public-map-grid"><Panel title="O que está acontecendo perto de você" subtitle="Ocorrências públicas agrupadas por região e categoria." action={<a className="btn btn-light" href="#/mapa">Abrir mapa completo</a>}><CityMap records={records} variant="public" onSelect={r => { location.hash='/mapa?regiao='+encodeURIComponent(r); }} /></Panel><Panel title="Perto de você" subtitle="Explore os relatos da cidade por região"><div className="near-list">{records.slice(0,5).map(r => <a key={r.id} href={'#/ocorrencias/'+r.id}><span className={'dot '+(r.priority === 'Alta' ? 'red' : 'amber')} /><div><strong>{r.title}</strong><small>{r.region}</small></div><Badge>{r.priority}</Badge></a>)}</div><a className="btn full-width" href="#/mapa">Ver todas as ocorrências</a></Panel></div>
    <div className="public-map-grid bottom-cta"><Panel title="Acompanhe seus relatos" subtitle="Veja o andamento, histórico e resposta da equipe municipal." action={<a className="btn" href="#/meus-relatos">Acessar meus relatos</a>}><span /></Panel><Panel className="blue-panel" title="Transparência da cidade" subtitle={`${s.rate}% das ocorrências da demonstração foram resolvidas.`} action={<a className="btn btn-blue" href="#/indicadores">Ver indicadores</a>}><span /></Panel></div>
  </>;
}
