import { useState } from 'react';
import { Filters, defaultFilters, filterRecords } from '../components/Filters';
import { Badge, Empty, PageHeading, Panel, Stats } from '../components/ui';
import { dateTime, exportCsv, stats } from '../helpers';
import { statuses, type Occurrence } from '../types';
export function Occurrences({ records, mine = false }: { records: Occurrence[]; mine?: boolean }) {
  const [filters,setFilters]=useState(defaultFilters); const visible=filterRecords(records,filters); const s=stats(records);
  return <>{mine ? <><PageHeading title="Meus relatos" subtitle="Acompanhe o andamento das ocorrências que você enviou para a cidade." action={<a className="btn" href="#/relatar">+ Novo relato</a>} /><Stats className="reports-stats" items={[{value:s.total,label:'Relatos enviados',color:'#2563eb'},{value:records.filter(r => r.status === 'Em análise' || r.status === 'Nova').length,label:'Em análise',color:'#7c3aed'},{value:records.filter(r => r.status === 'Programada' || r.status === 'Em execução').length,label:'Em andamento',color:'#f59e0b'},{value:s.resolved,label:'Resolvidos',color:'#10b981'}]} /></> : null}
    <Filters value={filters} onChange={setFilters} action={!mine ? <button className="btn" onClick={() => exportCsv(visible)}>Exportar CSV</button> : undefined} />
    <div className={mine ? 'reports-grid' : ''}><Panel title={mine ? 'Seus relatos' : 'Fila de ocorrências'} subtitle={`${visible.length} registros encontrados`}>
      {visible.length ? mine ? <div className="report-list">{visible.map(r => <article className="report-card" key={r.id}><div className="report-card-top"><div><h3>{r.title}</h3><small>{r.protocol}</small><p>{r.region} · enviado em {dateTime(r.createdAt)}</p></div><Badge>{r.status}</Badge></div><div className="report-progress"><div><small>Etapa atual</small><strong>{r.status === 'Resolvida' ? 'Ocorrência concluída' : r.status === 'Em execução' ? 'Equipe em campo' : r.status === 'Programada' ? 'Atendimento programado' : 'Triagem técnica'}</strong></div><progress max={4} value={statuses.indexOf(r.status)} aria-label={'Progresso de '+r.protocol} /><a className="btn" href={'#/ocorrencias/'+r.id}>Ver detalhes</a></div></article>)}</div>
      : <div className="table-scroll"><table><thead><tr><th>Ocorrência / protocolo</th><th>Categoria</th><th>Região</th><th>Prioridade</th><th>Status</th><th>Equipe</th><th aria-label="Ação" /></tr></thead><tbody>{visible.map(r => <tr key={r.id}><td><strong>{r.title}</strong><small>{r.protocol}</small></td><td>{r.category}</td><td>{r.region}</td><td><Badge>{r.priority}</Badge></td><td><Badge>{r.status}</Badge></td><td>{r.team || 'Não atribuída'}</td><td><a className="btn btn-light" href={'#/gestor/ocorrencias/'+r.id}>Detalhes</a></td></tr>)}</tbody></table></div> : <Empty />}
    </Panel>{mine ? <Panel title="Resumo do acompanhamento" subtitle="Visão rápida dos seus relatos"><div className="intelligence small-intelligence"><small>SEUS RELATOS</small><h3>{s.open} de {s.total} estão em andamento</h3><p>As atualizações feitas pelo gestor ficam registradas no histórico de cada ocorrência.</p><div className="mini-stats"><div><small>Tempo médio até solução</small><strong>{s.average}</strong></div><div><small>Taxa de solução</small><strong>{s.rate}%</strong></div></div></div><h3 className="spaced-title">Atualizações recentes</h3><div className="updates-list">{records.flatMap(r => r.history.map(h => ({...h,occurrence:r}))).sort((a,b) => b.createdAt.localeCompare(a.createdAt)).slice(0,3).map((h,i) => <a href={'#/ocorrencias/'+h.occurrence.id} key={i}><small>{dateTime(h.createdAt)}</small><strong>{h.title}</strong><p>{h.occurrence.title}</p></a>)}</div><a href="#/relatar" className="btn btn-teal full-width">Enviar um novo relato</a></Panel> : null}</div>
  </>;
}
