import { useState } from 'react';
import { Badge, Empty, Panel, Stats } from '../components/ui';
import { Filters, defaultFilters, filterRecords } from '../components/Filters';
import { statuses, teams, type Occurrence } from '../types';
import { stats } from '../helpers';
export function Teams({ records }: { records: Occurrence[] }) {
  const [filters,setFilters]=useState(defaultFilters); const visible=filterRecords(records,filters); const s=stats(records);
  const activeTeams=teams.filter(team => records.some(r => r.team === team && r.status !== 'Resolvida'));
  const maxLoad=Math.max(1,...teams.map(team => records.filter(r => r.team === team && r.status !== 'Resolvida').length));
  return <><Stats items={[{value:activeTeams.length,label:'Equipes ativas',note:'Com chamados em atendimento'},{value:records.filter(r => r.status === 'Em execução').length,label:'Chamados em execução',note:'Equipe em campo'},{value:s.resolved,label:'Concluídos',note:'No período selecionado'},{value:s.average,label:'Tempo médio de solução',note:'Calculado pelas conclusões'}]} /><Filters value={filters} onChange={setFilters} action={<a className="btn" href="#/relatar">+ Nova tarefa</a>} />
    <div className="teams-grid"><Panel title="Fluxo de atendimento" subtitle="Acompanhe as etapas e abra cada cartão para atribuir ou validar serviços." className="kanban-panel"><div className="kanban">{statuses.map((status,i) => { const items=visible.filter(r => r.status === status); return <section key={status} className={'kanban-column kanban-'+i}><h3>{status}<span>{items.length}</span></h3>{items.map(r => <a className="kanban-card" href={'#/gestor/ocorrencias/'+r.id} key={r.id}><h4>{r.title}</h4><p>{r.address}</p><Badge>{r.priority}</Badge><small>Responsável</small><strong>{r.assignees?.map(person=>person.name).join(', ') || r.team || 'Aguardando atribuição'}</strong><footer>{r.region}{r.dueAt ? ` · Prazo: ${new Date(r.dueAt).toLocaleDateString('pt-BR')}` : ''}</footer></a>)}{!items.length ? <span className="kanban-empty">Nenhum chamado</span> : null}</section>; })}</div>{!visible.length ? <Empty /> : null}</Panel>
      <Panel title="Capacidade das equipes" subtitle="Carga atual de chamados atribuídos"><div className="bar-list">{teams.map((team,i) => { const count=records.filter(r => r.team === team && r.status !== 'Resolvida').length; return <div key={team}><div className="bar-label"><span>{team}</span><strong>{count}</strong></div><div className="bar-track"><div style={{ width:`${count / maxLoad * 100}%`,background:['#ef4444','#f59e0b','#7c3aed','#10b981','#2563eb'][i] }} /></div><small>{count} em atendimento</small></div>; })}</div><div className="intelligence small-intelligence spaced-title"><small>INTELIGÊNCIA OPERACIONAL</small><h3>Distribuição com supervisão</h3><p>O gestor atribui o serviço, o colaborador registra a execução e o gestor valida a conclusão. O Kanban reflete o status persistido no banco.</p><a className="btn btn-teal full-width" href="#/gestor/ocorrencias">Organizar chamados</a></div></Panel></div>
  </>;
}
