import { useState } from 'react';
import { Badge, Empty, Panel, Stats } from '../components/ui';
import { Filters, defaultFilters, filterRecords } from '../components/Filters';
import { statuses, teams, type Occurrence } from '../types';
import { dateTime, stats } from '../helpers';

const isOverdue=(record:Occurrence)=>Boolean(record.dueAt&&new Date(record.dueAt).getTime()<Date.now()&&record.status!=='Resolvida');
export function Teams({ records }: { records: Occurrence[] }) {
  const [filters,setFilters]=useState(defaultFilters); const visible=filterRecords(records,filters); const s=stats(records);
  const activeTeams=teams.filter(team => records.some(record => record.team === team && record.status !== 'Resolvida'));
  const maxLoad=Math.max(1,...teams.map(team => records.filter(record => record.team === team && record.status !== 'Resolvida').length));
  const awaiting=records.filter(record=>record.status==='Aguardando validação').length;
  return <><Stats items={[{value:activeTeams.length,label:'Equipes ativas',note:'Com chamados em atendimento'},{value:records.filter(record => record.status === 'Em execução').length,label:'Chamados em execução',note:'Equipe em campo'},{value:awaiting,label:'Aguardando validação',note:'Ação necessária do gestor',color:'#2563eb'},{value:s.resolved,label:'Concluídos',note:'No período selecionado',color:'#10b981'}]} /><Filters value={filters} onChange={setFilters} action={<a className="btn" href="#/gestor/ocorrencias">Organizar chamados</a>} />
    <div className="teams-grid"><Panel title="Fluxo de atendimento" subtitle="Abra um cartão para atribuir, acompanhar ou validar cada serviço." className="kanban-panel"><div className="kanban">{statuses.map((status,index) => { const items=visible.filter(record => record.status === status); return <section key={status} className={'kanban-column kanban-'+index}><h3>{status}<span>{items.length}</span></h3>{items.map(record=><a className={'kanban-card '+(isOverdue(record)?'kanban-overdue':'')} href={'#/gestor/ocorrencias/'+record.id} key={record.id}><div className="kanban-card-top"><small>{record.protocol}</small><Badge>{record.priority}</Badge></div><h4>{record.title}</h4><p>{record.address}</p><dl className="kanban-details"><div><dt>Equipe</dt><dd>{record.team||'Não atribuída'}</dd></div><div><dt>Colaborador</dt><dd>{record.assignees?.map(person=>person.name).join(', ')||'Aguardando atribuição'}</dd></div></dl><footer><span>{record.region}</span>{record.dueAt?<time className={isOverdue(record)?'overdue-text':''}>{isOverdue(record)?'Prazo vencido':`Prazo ${dateTime(record.dueAt)}`}</time>:<span>Sem prazo</span>}</footer></a>)}{!items.length ? <span className="kanban-empty">Nenhum chamado</span> : null}</section>; })}</div>{!visible.length ? <Empty /> : null}</Panel>
      <Panel title="Capacidade das equipes" subtitle="Carga atual de chamados atribuídos"><div className="bar-list">{teams.map((team,index) => { const count=records.filter(record => record.team === team && record.status !== 'Resolvida').length; return <div key={team}><div className="bar-label"><span>{team}</span><strong>{count}</strong></div><div className="bar-track"><div style={{ width:`${count / maxLoad * 100}%`,background:['#ef4444','#f59e0b','#7c3aed','#10b981','#2563eb'][index] }} /></div><small>{count} em atendimento</small></div>; })}</div><div className="intelligence small-intelligence spaced-title"><small>FILA DE VALIDAÇÃO</small><h3>{awaiting ? `${awaiting} serviço(s) aguardam decisão` : 'Nenhum serviço aguardando validação'}</h3><p>O gestor atribui o serviço, o colaborador registra a execução e somente o gestor valida a conclusão.</p><a className="btn btn-teal full-width" href="#/gestor/ocorrencias">Abrir fila de ocorrências</a></div></Panel></div>
  </>;
}
