import { useEffect, useState } from 'react';
import { useData, useRoute } from './data';
import { inPeriod } from './helpers';
import { ManagerLayout, PublicLayout } from './components/Layout';
import { ErrorBox } from './components/ui';
import { Home } from './pages/Home';
import { Dashboard } from './pages/Dashboard';
import { Report } from './pages/Report';
import { MapPage } from './pages/MapPage';
import { Occurrences } from './pages/Occurrences';
import { Detail } from './pages/Detail';
import { Alerts } from './pages/Alerts';
import { Teams } from './pages/Teams';
import { Indicators } from './pages/Indicators';
import { Information } from './pages/Information';
export default function App() {
  const fullRoute=useRoute(); const [route,query='']=fullRoute.split('?'); const manager=route.startsWith('/gestor');
  const [period,setPeriod]=useState('7'); const { records,mine,loading,error,refresh }=useData();
  const periodRecords=inPeriod(records,period); const initialRegion=new URLSearchParams(query).get('regiao') || '';
  useEffect(() => { document.title=(manager ? 'Gestor' : 'Cidade')+' • ObservaMarília'; },[manager]);
  let content;
  if(route === '/relatar') return <Report />;
  if(route === '/acesso') content=<Information access />;
  else if(route === '/') content=<Home />;
  else if(route === '/gestor') content=<Dashboard records={periodRecords} />;
  else if(route === '/mapa' || route === '/gestor/mapa') content=<MapPage key={fullRoute} records={manager ? periodRecords : records} manager={manager} initialRegion={initialRegion} />;
  else if(route === '/meus-relatos') content=<Occurrences records={mine} mine />;
  else if(route === '/gestor/ocorrencias') content=<Occurrences records={periodRecords} />;
  else if(/^\/(gestor\/)?ocorrencias\/[^/]+$/.test(route)) content=<Detail key={route} id={route.split('/').pop()!} manager={manager} />;
  else if(route === '/gestor/alertas') content=<Alerts records={periodRecords} />;
  else if(route === '/gestor/equipes') content=<Teams records={periodRecords} />;
  else if(route === '/indicadores' || route === '/gestor/indicadores') content=<Indicators records={manager ? periodRecords : records} manager={manager} />;
  else if(route === '/como-funciona' || route === '/gestor/configuracoes') content=<Information settings={manager} />;
  else content=<div className="empty"><h1>Página não encontrada</h1><a className="btn" href="#/">Voltar ao início</a></div>;
  const body=<>{error ? <div className="connection-error"><ErrorBox error={error} /><button className="btn" onClick={() => void refresh()}>Tentar novamente</button></div> : null}{loading ? <div className="loading" role="status">Carregando dados da cidade…</div> : content}</>;
  return manager ? <ManagerLayout route={route} period={period} setPeriod={setPeriod}>{body}</ManagerLayout> : <PublicLayout>{body}</PublicLayout>;
}
